import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Content from "../components/Content";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Sweepstake</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Content />
		</div>
	);
};

export default Home;
