import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Sweepstake</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<p className="text-slate-200">Hello </p>
			</div>
		</div>
	);
};

export default Home;
